# netlify.toml
[build]
  command = "echo 'No build command needed for static site + functions'"
  publish = "." # Dossier racine contenant index.html
  functions = "api" # Dossier des fonctions

[functions]
  node_bundler = "esbuild"
  # node_version = "18" # Décommentez si nécessaire
  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Souvent utile pour les routes API
  